config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
	root  "posts#index"
  devise_for :users
  resources :posts do
  	resources :postscomments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
belongs_to :user
has_many :postscomments

end

app/models/postscomment.rb
class Postscomment < ApplicationRecord
	belongs_to :user
	belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :postscomments
  has_many :posts
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :devise_sign_up_params, if: :devise_controller?


private

def devise_sign_up_params
devise_parameter_sanitizer.permit(:sign_up, keys:[:attribute, :nickname,:avatar ])
end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except:[:show,:index]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comments=Postscomment.where(post_id: @post.id)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    params[:post][:user_id]=current_user.id
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body,:user_id)
    end
end

app/controllers/postscomments_controller.rb
class PostscommentsController < ApplicationController
	before_action :authenticate_user! 

def create
params[:postscomment][:post_id] = params[:post_id]
params[:postscomment][:user_id] = current_user.id
pp @postscomment = Postscomment.create(postscomments_params)
if @postscomment.save
else
@postscomment.errors.full_messages.each do |msg|
@msg = msg
end
flash[:notice] = "#{@msg}"
end
redirect_to post_path(params[:post_id])
end

private
def postscomments_params
params.require(:postscomment).permit(:user_id, :post_id, :text)

end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/postscomments_helper.rb
module PostscommentsHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer container" style="background-color: #333; color: white; padding: 50px 30px">
		<div class="row">
			<div class="col-lg-3" style="margin-top: 100px">
				All @ copiright</div>
			<div class="col-lg-6">
				<h2>title</h2>
				Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
				tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
				quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
				consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
				cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
				proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
				Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
				tempor
			</div>
			<div class="col-lg-3" style="margin-top: 100px">
				adrres: Zahoretska 99 <br>
				mail blog@gmail.com <br>
				phone: +4523452432
			</div>
		</div>	
	</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">BLOG</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to 'New Post', new_post_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
         <% if current_user.nil? %>
			  <li><%= link_to user_session_path do %> Log In </li>
			<%end%>
			<% else %>
			<li><%= link_to destroy_user_session_path, method: :delete do %>Log Out</li>
			<%end%>
		<% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogForZalik</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">


<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'layouts/navbar'%>
    	<%= yield %>
      <%= render 'layouts/footer'%>
	</div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title %>
  </div>

  <div class="field">
    <%= form.label :body %>
   <%= form.text_area :body, :class => "tinymce", :rows => 40, :cols => 50 %>
   <%= tinymce %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>
<%= link_to 'New Post', new_post_path %>
<table>
  <thead>
      <th colspan="3"></th>
  </thead>

  <tbody>
        <% @posts.each do |post| %>
        <div class="panel panel-default">
        <div class="panel-body"><h3><%= post.title %></h3></div><br>
        <div class="panel-footer"><h4><%= post.body %></h4>
        <%= link_to 'Show ', post %>
        <%= link_to 'Edit ', edit_post_path(post) %>
        <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
      </div>
    <% end %>
  </tbody>
</table>

<br>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-default">
        <div class="panel-body"><h3><%= @post.title %></h3></div><br>
        <div class="panel-footer"><h4><%=sanitize @post.body %></h4>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>
</div>

<% @comments.each do |comment| %>
<div class="panel panel-info">
        <div class="panel-body"><h3><%= comment.user.nickname %></h3></div>
        <div class="panel-footer"><h4><%=comment.text%></h4></div>
  </div>

<% end%>

<%= form_for :postscomment, url: post_postscomments_path(@post.id) do |f| %>

    <% if flash[:notice] %>
        <div class="notice"> <%= flash[:notice] %> </div>
    <% end %>
    <div align="center">
    <p><%= f.label "Write Comment" %></p>
    <%= f.text_area :text, cols: 10, rows: 5 %><br />
    <br/>
    <p><%= f.submit "Send", class: "btn btn-primary active"%></p><br/></div>
<%end%>